# Generated by Django 5.0.3 on 2024-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('std_fname', models.CharField(max_length=50)),
                ('std_lname', models.CharField(max_length=50)),
                ('std_birth_date', models.DateField()),
                ('std_email', models.CharField(max_length=100)),
                ('prog_id', models.IntegerField()),
            ],
        ),
    ]
